# Modélisation statistique des données MG112

## Load librairies

```{r}
library(tidyverse)
library(gghighlight)
```

## Load and inspect data

```{r}
grainsize <- read_csv("data/grainsize.csv", show_col_types = FALSE)
soils <- read_csv("data/soils.csv", show_col_types = FALSE)
proctor <- read_csv("data/proctor.csv", show_col_types = FALSE)
fuseau <- read_csv("data/fuseaux.csv", show_col_types = FALSE)
field <- read_csv("data/field.csv", show_col_types = FALSE)

grainsize$Soil_ID <- sprintf("%002d", grainsize$Soil_ID)
soils$Soil_ID <- sprintf("%002d", soils$Soil_ID)
proctor$Soil_ID <- sprintf("%002d", proctor$Soil_ID)
field$Soil_ID <- sprintf("%002d", field$Soil_ID)

soils <- soils |>
  mutate(Metatype = case_when(
    Type == "MG112" ~ "MG112",
    Type == "CG14" ~ "MG112",
    Type == "Sable" ~ "MG112",
    Type == "MG20" ~ "MG20",
    Type == "MR-5" ~ "MG112",
    TRUE ~ "OUT"
  )) |> 
  filter(Metatype != "OUT")

grainsize <- grainsize |>
  left_join(soils, by = "Soil_ID") |> 
  filter(Metatype != "OUT")

proctor <- proctor |>
  left_join(soils, by = "Soil_ID") |> 
  filter(Metatype != "OUT")

field <- field |>
  left_join(soils, by = "Soil_ID") |> 
  filter(Metatype != "OUT")
```

```{r}
write_csv(grainsize %>% select(Grainsize_ID, Soil_ID, Mesh, Perc_passing, Metatype), "data/r_grainsize.csv")
write_csv(proctor %>% select(Proctor_ID, Soil_ID, `Density_kg/m3`, `MassWC_%`, `VolWC_%`, `DegreeSat_%`, Probe, IsPVC), "data/r_proctor.csv")
write_csv(soils, "data/r_soils.csv")
write_csv(field, "data/r_field.csv")
```

```{r fig.height=4, fig.width=4}
grainsize  |> 
  select(Soil_ID, Mesh, Perc_passing, Metatype) |> 
  drop_na() |> 
  mutate(Soil_ID = paste("Sol ID: ", Soil_ID, " - ", Metatype)) |> 
  ggplot() +
  facet_wrap(~Soil_ID, ncol = 4) +
  geom_ribbon(
    data = fuseau |> pivot_wider(names_from = Limit, values_from = Perc_passing),
    mapping = aes(x=Mesh, ymin = Min, ymax = Max, fill = Metatype),
    alpha = 0.3
  ) +
  geom_line(mapping=aes(x=Mesh, y=Perc_passing, group=Soil_ID)) +
  labs(
    title = "Courbes granulométriques des sols",
    x = "Dimension des mailles du tamis (mm)",
    y = "Pourcentage passant"
  ) +
  scale_x_continuous(trans='log10') +
  scale_fill_manual(values=c('#edf0e9', '#018748')) +
  gghighlight() +
  theme_minimal()
ggsave('images/granulos.png', height = 8, width = 8)
```
