[project]
name = "sherbrooke_method_ml"
description = "Supplementary material for manuscript Machine learning-based regression models to improve compaction control prediction when applying the Sherbrooke Method"
readme = "README.md"
version = "0.1.0"
requires-python = ">=3.11,<3.13"
dependencies = [
    "numpy>=1.24.0,<2.0.0",
    "pandas>=2.2.0",
    "polars>=1.14.0",
    "scipy>=1.14.0",
    "scikit-learn>=1.5.0",
    "optuna>=4.1.0",
    "matplotlib>=3.9.0",
    "seaborn>=0.13.0",
    "altair>=5.4.0",
    "statsmodels>=0.14.0",
    "pymc>=5.15.0",
    "pytensor>=2.20.0",
    "marimo>=0.16.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
only-include = ["README.md"]
